// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace MidStateShuttleService.Models;

[Table("CheckIn")]
public partial class CheckIn
{
    [Key]
    public int CheckInId { get; set; }

    public string? Name { get; set; }

    public DateTime Date { get; set; }

    [StringLength(255)]
    public string? Comments { get; set; }

    public bool FirstTime { get; set; }

    /// <summary>
    /// This is pick up location id
    /// </summary>
    public int LocationId { get; set; }

    public bool IsActive { get; set; }

    [StringLength(25)]
    public string? StudentId { get; set; }

    public int DropOffLocationId { get; set; }

    /// <summary>
    /// This is the pick up location resolved in the check in service
    /// </summary>
    [ForeignKey("LocationId")]
    public virtual Location Location { get; set; }

    /// <summary>
    /// Drop off location resolved in the check in service.
    /// </summary>
    [ForeignKey("DropOffLocationId")]
    public virtual Location DropOffLocation { get; set; }
}